# oneDark
[colors]
foreground= '#abb2bf'
background= '#282C34'
cursor_bg = "#d0d0d0"
cursor_border = "#d0d0d0"
cursor_fg = "#151515"
selection_bg = "#444444"
selection_fg = "#c5c8c6"

ansi=[ "#1e2127", "#e06c75", "#98c379", "#d19a66", "#61afef", "#c678dd", "#56b6c2", "#abb2bf", ]
brights=[ "#5c6370", "#e06c75", "#98c379", "#d19a66", "#61afef", "#c678dd", "#56b6c2", "#ffffff",] 

# ansi = ["#000000","#fd5ff1","#87c38a","#ffd7b1","#85befd","#b9b6fc","#85befd","#e0e0e0"]
# brights = ["#000000","#fd5ff1","#94fa36","#f5ffa8","#96cbfe","#b9b6fc","#85befd","#e0e0e0"]
