# oneLight
[colors]
foreground= '#2a2b33'
background= '#fafafa'
cursor_bg = "#bbbbbb"
cursor_border = "#bbbbbb"
cursor_fg = "#ffffff"
selection_bg = "#ededed"
selection_fg = "#2a2c33"

ansi = [ "#000000", "#de3d35", "#3e953a", "#a06600", "#2f5af3", "#a00095", "#3e953a", "#bbbbbb", ]
brights = [ "#000000", "#de3d35", "#3e953a", "#a06600", "#2f5af3", "#a00095", "#3e953a", "#ffffff", ]

# ansi = ["#000000","#de3e35","#3f953a","#d2b67c","#2f5af3","#950095","#3f953a","#bbbbbb"]
# brights = ["#000000","#de3e35","#3f953a","#d2b67c","#2f5af3","#a00095","#3f953a","#ffffff"]
